# Use a base image with necessary dependencies
FROM ubuntu:latest

# Install necessary tools and dependencies
RUN apt-get update && \
    apt-get install -y curl git bash && \
    apt-get clean

COPY ./configs/config.json .
# Install Dojoup
RUN curl -L https://install.dojoengine.org | bash

# Add Dojoup directory to PATH
ENV PATH="/root/.dojo/bin:${PATH}"

# Expose any necessary ports if applicable
EXPOSE 5050

RUN dojoup -v 0.4.4

# Set the default command to run when the container starts
CMD katana --host 0.0.0.0 --messaging config.json