version: "3.8"

services:
  anvil:
    build:
      context: .  # Set the Docker context to the current directory
      dockerfile: Dockerfile.anvil  # Specify the custom Dockerfile name
    ports:
      - "8545:8545"
    volumes:
      - ./anvil-chains:/chains