name: Docker Deployment
on:
  push:
    branches:
      - feat/l1-l2-messaging

jobs:
  build:
    name: Building CI pipeline on Ubuntu OS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Check if Docker is installed
        run: |
          if ! command -v docker &> /dev/null
          then
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo apt-get install -y docker-compose
          fi

      - name: Set up Docker Compose
        run: |
          cd ./integration_tests
          docker-compose up -d --build
        working-directory: ${{ github.workspace }}

      - name: Deploy contracts on both the chains
        run: docker-compose logs -f contracts
        working-directory: ./integration_tests

      - name: Check l1-l2 message passing and print results
        run: bash ./scripts/test_messaging.sh
        working-directory: ./integration_tests
        shell: bash
