name: Docker Deployment
on:
  push:
    #will change the default branch to main once its merged to main branch
    branches:
      - feat/github-workflow

jobs:
  build:
    name: Building CI pipeline on Ubuntu OS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Check if Docker is installed
        run: |
          if ! command -v docker &> /dev/null
          then
              apt-get update
              apt-get install -y docker.io
              apt-get install -y docker-compose
          fi

      - name: Change directory to Docker Compose folder
        run: |
          cd monodock
          ls -la

      - name: Run docker-compose
        run: docker-compose up -d

      - name: Sleep for 60 seconds for waiting container to initialize the processing
        run: |
          sleep 60s

      - name: Check Running and Exit Status for Docker containers
        run: ./scripts/check_containers.sh
