name: State Bridge L2 Testing

on:
  push:
    branches:
      - main
      - organize_and_clean

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install scarb 2.8.0
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh -s -- -v 2.8.0

      - name: Install Starknet Foundry
        run: |
          curl -L https://raw.githubusercontent.com/foundry-rs/starknet-foundry/master/scripts/install.sh | bash
          snfoundryup

      - name: Set PATH environment variable
        run: echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Check versions
        run: |
          scarb --version
          snforge --version

      - name: Build contract with scarb
        run: |
          cd state_bridge
          scarb build

      - name: Run tests with snforge
        run: |
          cd state_bridge
          snforge test