name: State Bridge L2 Testing

on:
  push:
    branches:
      - main
      - 'dev/*' 

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Foundry 
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          echo "Checking Foundry installation..."
          echo "Contents of home directory:"
          ls -la $HOME
          echo "Contents of .foundry directory (if it exists):"
          ls -la $HOME/.foundry || echo ".foundry directory not found"
          echo "Contents of .foundry/bin directory (if it exists):"
          ls -la $HOME/.foundry/bin || echo ".foundry/bin directory not found"
          echo "Searching for foundryup:"
          find $HOME -name foundryup
          echo "Current PATH:"
          echo $PATH
          echo "Trying to locate foundryup in PATH:"
          which foundryup || echo "foundryup not found in PATH"
          export PATH="$HOME/.foundry/bin:$PATH"
          foundryup || $HOME/.foundry/bin/foundryup

      - name: Install Scarb 2.8.2
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh -s -- -v 2.8.2

      - name: Install Starknet Foundry
        run: |
          curl -L https://raw.githubusercontent.com/foundry-rs/starknet-foundry/master/scripts/install.sh | bash
          snfoundryup

      - name: Set PATH environment variable
        run: echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
          
      - name: Check versions
        run: |
          scarb --version
          snforge --version
          foundry --version

      - name: Build contract with scarb
        run: |
          cd state_bridge_l2/world_id_state_bridge
          scarb build

      - name: Run tests with snforge
        run: |
          cd state_bridge_l2/world_id_state_bridge
          snforge test 

      - name: Run tests for L1
        run: |
          cd state_bridge_l1
          cp anvil.env .env
          source .env
          forge test